### ISSUE TITLE
links in example accordion

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#40]
see page 2.2, example 4
so can we not add links within the text of the accordion?

**Comment by evansavage** [comment]
We can, it just involves manually HTML coding the example box instead of using the {% include ... %} syntax. Here is the HTML code for the example_accordion:

Code with custom title:

```
<div class="outer-accordion-wrapper">
  <div class="example-text-wrapper">
      <h4 class="include-title">*TITLE HERE*</h4>
    <div class="close">+</div>
    <div class="open">-</div>
  </div>
  <div class="example-wrapper">
    *EXAMPLE TEXT HERE with links in <a> tags if needed*
  </div>
</div>
```

Code without custom title 

```
<div class="outer-accordion-wrapper">
  <div class="example-text-wrapper">
      <h4>{{ site.data.translations.exampleText[page.lang] }} </h4>
    <div class="close">+</div>
    <div class="open">-</div>
  </div>
  <div class="example-wrapper">
    *EXAMPLE TEXT HERE with links in <a> tags if needed*
  </div>
</div>
```

The two need to be different so javascript can handle the numbering correctly. Notice the differences in the h4 title element between the two cases

**Comment by macdonaldc** [comment]
thanks!
